### ISSUE TITLE
Port to Node.js

### ISSUE THREAD

**Issue by darcyclarke** [zmoazeni/csscss#65]
Would love to see this ported to node and eventually have a client-side version you could throw into a bookmarklet. Think it would be super handy as a dev tool. Not sure the time investment but I think it would be worth it. Thoughts?

**Comment by niutech** [comment]
The node.js version wouldn't require Ruby as a dependency when run from Grunt/Gulp. The bookmarklet would allow web devs to audit existing websites, like [YSlow](http://yslow.org/mobile).

Maybe it is possible to port CSSCSS to JS using [Opal](http://opalrb.org/)?
